### ISSUE TITLE
[VpKaNIzpIsae3d2So8wN531cKB52] Carrusel Variantes

### ISSUE THREAD

**Issue by speechsigns** [speechsigns/signamed-public#42]
Cuando hay mas de una variante y las imágenes son de diferente tamaño temblequea hasta que se ajusta a la más pequeña. Si solo aparece la del DILSE la imagen sale más grande, demasiado.
Supongo que cambiando el tamaño de las imágenes del DILSE para que sean iguales a las de FAXPG, se arreglaría.

**Comment by AdrianSantas** [comment]
Para descartar posibles cuestiones de tamaños y formatos, estaría bien confirmar si se están utilizando los vídeos que había adaptado en su momento, tanto en cuanto a las definiciones como las variantes.

**Comment by speechsigns** [comment]
Resuelto. Muchas gracias por su reporte
