### ISSUE TITLE
[W7jKzqpvGCc1NbT06gWreyPkImH3] Bug_Report - Filtros-Info_id_propietario

### ISSUE THREAD

**Issue by speechsigns** [speechsigns/signamed-public#60]
Al seleccionar los filtros. 
  + Añadir dos botones uno para quitarlos todos los filtros y otro para seleccionar todos.

El retorno de incidencias - retorna tanto las abiertas como cerradas y el "user_id"
  + Añadir filtro según estado: Abierto & Cerrado. Por defecto mostrar sólo incidencias abiertas.
  + Añadir una nueva columna para mostrar el id del propietario de la incidencia.

**Comment by AdrianSantas** [comment]
Está todo listo excepto el último punto, añadir una nueva columna con el id de usuario, debido a las siguientes cuestiones:

- El retorno de incidencias actual no incluye el "user_id", por lo que la columna quedaría vacía por el momento.
- El formato actual de "user_id" es algo ilegible para un usuario común (según lo visto en el archivo de ejemplo del que dispongo), y puede acabar causando mayor confusión que utilidad. Quizás una alternativa podría ser detectar si el "user_id" de cada incidencia coincide con la del usuario actual, y renderizar distintos iconos o textos que le hagan entender si la incidencia la ha abierto él/ella u otro usuario distinto.

**Comment by AdrianSantas** [comment]
Incidencia resuelta y añadidas opciones extras de filtros comentadas en la reunión por meet.

Finalmente, el tema de la ausencia del "user_id" era fallo mío, estaba cogiendo la información de donde no debía.

Aprovecho para poner la etiqueta de "incidencia_resuelta", puede sernos útil para informar de que algo debería de estar resuelto por si se quiere comprobar antes de cerrar la incidencia.
