### ISSUE TITLE
[yrevRlMj2fQ2TTJzvwOt9fvIzlE2] No aparece "grabar variante"

### ISSUE THREAD

**Issue by speechsigns** [speechsigns/signamed-public#71]
Hola. Entro a signamed (no como invitado) sino como usuario registrado y cuando entro desde la lupa a la sección de texto y de una palabra/signo voy a sus variantes, no me parece debajo la opción de "grabar variante" para poder introducirla

**Comment by mvazquezgts** [comment]
Solucionado, hemos corregido los permisos aplicados a los usuarios recién registrados.
Muchas gracias por su reporte.

Quedamos a su disposición.
