### ISSUE TITLE
[d1jgq6P1rqZAnMmRhKpdA5xhsdR2] No se muestra el vídeo que se está grabando. Pantalla en negro

### ISSUE THREAD

**Issue by speechsigns** [speechsigns/signamed-public#76]
El módulo de grabación presenta en negro la pantalla de la cámara mientras graba.Luego lo reproduce bien.

**Comment by mvazquezgts** [comment]
¿ Me puede indicar el dispositivo que está utilizando, pc, ipad o móvil y que navegador ?
¿ Su dispositivo cuenta con más de una cámara conectada ?
Muchas gracias
